paths:
  raw_data: "/raw_data/umcu_median"
  checkpoints: "/training/factorecg/ef"
  training_labels: "/training/secondary_task/train_ef_40.csv"
  validation_labels: "/training/secondary_task/test_ef_40.csv"
  pretrain_checkpoint: ~
training:
  label_names: Label
  learning_rate: 0.0005
  batch_size: 128
  epochs: 15
  loss_weights: 1
  pretrain: false
  tags:
    - EF < 40
  project_name: UMCUtrecht/FactorECG-supervised
network:
  in_channels: 12
  channels: 128
  depth: 7
  reduced_size: 64
  out_channels: 1
  kernel_size: 5
  dropout: 0.3
  softplus_eps: 1.0e-4
  sd_output: false
